### ISSUE TITLE
Set up issue templates/forms for Revolt's repos

### ISSUE THREAD

**Issue by Rexogamer** [revoltchat/revolt#208]
These will make bug reports/feature requests easier to create. See [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for more info on setting these up.

**Comment by shahriaarrr** [comment]
Hello
I can help you to setup issue templates.
Can I do this for you?

**Comment by shahriaarrr** [comment]
Hello
I can help you to setup issue templates.
Can I do this for you?
@insertish

**Comment by Rexogamer** [comment]
I was actually considering self-claiming this issue - will post here with any further updates.

**Comment by jbays92** [comment]
i cant access voice channels

**Comment by insertish** [comment]
This was solved months ago.
