### ISSUE TITLE
Native iOS App

### ISSUE THREAD

**Issue by JoshAtticus** [revoltchat/revolt#385]
### What do you want to see?

I know you can use PWA for iOS, but for me, app.revolt.chat doesn't load. It might be possible to make an app and allow people to sideload the IPA file, or use testflight; with support for  up to 10,000 users; which is free instead of the App Store with its $99 p/year fee.

**Comment by UnixPhonez** [comment]
this is a good idea, I'd like a invite link when this goes live on testflight

**Comment by JoshAtticus** [comment]
Turns out it was just my old phone, although a testflight would still be nice so it isn't laggy like a safari pwa

**Comment by UnixPhonez** [comment]
great to see the status of this issue has been changed to in progress, can't wait for the beta

**Comment by FillingTheVoidOnYT** [comment]
would be great to have an testflight

**Comment by therealonlygithub1** [comment]
this would be a great idea

**Comment by JoshAtticus** [comment]
Good to see that the status is set to in progress!!!

**Comment by JoshAtticus** [comment]
And for a little bit of clarity, testflight essentially allows you to share a native iOS app with up to 10,000 iOS devices for free, and if that limit is reached, you can just make another testflight. While it does require a mac, so does deploying to the app store :)

**Comment by insertish** [comment]
Moving back since the original PR is now inactive.

**Comment by JoshAtticus** [comment]
Sad

**Comment by Rexogamer** [comment]
Update: Zoma will start development on the native iOS app very soon (we're getting the necessary hardware tomorrow) ^^

**Comment by JoshAtticus** [comment]
> Update: Zoma will start development on the native iOS app very soon (we're getting the necessary hardware tomorrow) ^^

Woohoo! I can do testing on my devices. I have an iPhone 8, iPhone 12, iPad 6th Gen, and an iPad Pro 2020

**Comment by ryan-roche** [comment]
Absolutely willing and able to assist with testing. Current hardware is an iPhone 14 Pro and 2018 iPad Pro

**Comment by andreyrd** [comment]
Is there any reason the iOS app isn't currently open source? I have iOS experience and would be willing to contribute a little.

**Comment by insertish** [comment]
It's just that it's still in heavy development, I could forward an inquiry if you're interested in helping out?
Currently Zomatree maintains the iOS app.

**Comment by jwmh** [comment]
I’m using an iPhone 7.
iOS 15
(Hoping Zonia be able to build for that)

**Comment by tjb** [comment]
I would be interested in helping out too @insertish if Zomatree needs some extra hands

**Comment by insertish** [comment]
actually i will just recreate the issue since this is going on a special project board
https://github.com/revoltchat/revolt/issues/690
