### ISSUE TITLE
bug: Network Error

### ISSUE THREAD

**Issue by IveMalfunctioned** [revoltchat/revolt#412]
### What happened?

Sorry if this is the wrong repository to report this to, but any time I try to upload an image to a server icon or banner, it doesn't work and I get this error.
![image](https://user-images.githubusercontent.com/20033421/184701014-ad129f06-df22-46c9-8956-c97710500038.png)
Tried relogging and refreshing many times, even waited a few days, still no dibs.

[11a17fe](https://github.com/revoltchat/revite/commit/11a17feaae022c29ae972c30240692b4088a94d9) [(master)](https://github.com/revoltchat/revite/tree/master)
Nightly 1.0.1
API: 0.5.5
revolt.js: 6.0.2

**Comment by Rexogamer** [comment]
If this is still an issue on both Nightly and production (`app.revolt.chat`), please re-open this in [Revite's repository](https://github.com/revoltchat/revite/issues/new/choose), preferably with console logs. Thanks!
