### ISSUE TITLE
When I click a voice channel, it doesn't join. Or when I click call button on my homies group. Nothing happens. They experience the same problem. Is this an issue or a bug?

### ISSUE THREAD

**Issue by dx7v2** [revoltchat/revolt#427]
When I click a voice channel, it doesn't join. Or when I click call button on my homies group. Nothing happens. They experience the same problem. Is this an issue or a bug?

_Originally posted by @dx7v2 in https://github.com/revoltchat/revolt/discussions/426_

**Comment by Rexogamer** [comment]
Answered in the discussion.
