### ISSUE TITLE
feature request: Ability to add slowmode to a channel. Also, the ability to see what the server is like from another role temporarily.

### ISSUE THREAD

**Issue by Oglo12** [revoltchat/revolt#507]
### What do you want to see?

I love Revolt, but these features would really help keep the chat roles organized and what not. Discord has these features, and it is lovely! I think these simple features would really help people grow communities on Revolt, and not accidentally screw up a roles permissions!

**Comment by Rexogamer** [comment]
Wrong repo; you'll want revoltchat/backend for the initial implementation of these features.
