### ISSUE TITLE
bug: perma mute, cannot unmute, after restart, relogin, and many others

### ISSUE THREAD

**Issue by Meatysasquatchh** [revoltchat/revolt#514]
# bug: perma mute, cannot unmute, after restart, relogin, and many others

**Comment by Rexogamer** [comment]
Three things: 
- This repo is for organisation wide planning/maintenance only 
- These mostly sound like bugs with the client, which is [being rewritten](https://github.com/revoltchat/frontend)
- This issue is also pretty vague; in future, try to elaborate on the bugs you're facing
