### ISSUE TITLE
ability to make a link to someones profile

### ISSUE THREAD

**Issue by EinfachRuwen** [revoltchat/revolt#581]
### Discussed in https://github.com/orgs/revoltchat/discussions/247

<div type='discussions-op-text'>

<sup>Originally posted by **ghost** November 16, 2021</sup>
There should be an ability to create or copy a link which leads to your profile. E.g. https://app.revolt.chat/user/exampleusername or https://app.revolt.chat/user/exampleuuid</div>

**Comment by insertish** [comment]
This is a meta repo and not intended for any issue, please use discussions.
