### ISSUE TITLE
Animate a user icon temporarily upon joining a voice channel to make it easier for existing members to identify the joined member.

### ISSUE THREAD

**Issue by aalekhpatel07** [revoltchat/revolt#623]
### Discussed in https://github.com/orgs/revoltchat/discussions/622

<div type='discussions-op-text'>

<sup>Originally posted by **aalekhpatel07** September 26, 2023</sup>
Currently, when a user joins a voice channel, there is no indication of the identity of the joined member. The members of the channel would have to go through the list manually to identify who joined the call. This can become a lot of work in sufficiently large parties.

As a potential fix, could we highlight, or blink, or animate in some way, the acknowledgement of a member joining the call? This could be a temporary thing for, say, 3s to help the other members identify the joined member.

My apologies if there's another feature that already solves this problem, in which case, I'd love to learn about its usage.

Thanks</div>

**Comment by Rexogamer** [comment]
Closing in favour of discussion/per repo scope.
