### ISSUE TITLE
bug: Can't delete emojis

### ISSUE THREAD

**Issue by EthanWinters2885** [revoltchat/revolt#637]
### What happened?

Expected Result: Emoji would delete

the actual result: Delete button doesn't do anything

**Comment by Rexogamer** [comment]
Reload the page - is the emoji still there?

**Comment by EthanWinters2885** [comment]
no

**Comment by Rexogamer** [comment]
In that case, closing as a Revite issue (Revite is deprecated, and the emoji is being deleted so it's just not rerendering).
