### ISSUE TITLE
bug: Masquerading pfps don't work properly anymore

### ISSUE THREAD

**Issue by EthanWinters2885** [revoltchat/revolt#658]
### What happened?

Ever since the platform somehow died on December 31, 2023, Masquerading with custom pfps now just appears with a square and the default image icon

Expected Result:
Image would appear like normal before the platform died for a few hours

Actual Result:
![image](https://github.com/revoltchat/revolt/assets/90074580/f8d21861-a8c6-4d92-b3a7-77335837c781)

**Comment by amycatgirl** [comment]
The image proxy, January, is currently down. Please see https://status.revolt.chat
