### ISSUE TITLE
feature request: PUSH notifications for mobile/desktop/web app

### ISSUE THREAD

**Issue by MrDrag0nXYT** [revoltchat/revolt#671]
### What do you want to see?

PUSH notifications of messages, calls, mentions, replies and any other activities, related to user

**Comment by insertish** [comment]
These exist but are only implemented for DMs and mentions.
Superseding with these issues:
https://github.com/revoltchat/backend/issues/309
https://github.com/revoltchat/backend/issues/310
https://github.com/revoltchat/backend/issues/311
