### ISSUE TITLE
Viewing server as a role

### ISSUE THREAD

**Issue by therealdylansteele** [revoltchat/revolt#677]
### Discussed in https://github.com/orgs/revoltchat/discussions/588

<div type='discussions-op-text'>

<sup>Originally posted by **vico93** July  3, 2023</sup>
Be able to test server roles by simulating how the server would present to them would be a huge benefit for server owners. I hope this feature from Discord could be emulated by Revolt as well.

[Reference for how Discord implements this](https://support.discord.com/hc/en-us/articles/360055709773-View-as-Role-FAQ).</div>

I feel like this is a must have feature for security reasons as people may wish to mark some of their channels as private such as moderator only, bug reports etc

**Comment by Rexogamer** [comment]
I think there's some confusion here - we already have private channels?

**Comment by therealdylansteele** [comment]
> I think there's some confusion here in the last bit of your message - we already have private channels?

Its vital that users are able to preview these changes as its easy to miss setting up the specific privacy settings plus we may want role specific channels.

**Comment by insertish** [comment]
This is a meta repo for managing the project, please use the discussion forum (which you've linked) for further comments.
